# Generated by Django 4.2 on 2024-10-27 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enfermedades',
            fields=[
                ('ID_Enfermedades', models.AutoField(primary_key=True, serialize=False)),
                ('Codigo_Enfermedades', models.CharField(max_length=10, unique=True, verbose_name='Codigo de enfermedad')),
                ('Descripcion', models.CharField(max_length=200, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name_plural': 'Enfermedades',
            },
        ),
    ]
