# Generated by Django 4.2 on 2024-11-03 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enfermedades', '0001_initial'),
        ('cita', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='Fecha_de_Cita',
            field=models.DateField(verbose_name='Fecha para cita'),
        ),
        migrations.AlterField(
            model_name='detalle_cita',
            name='ID_Enfermedades',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='enfermedades.enfermedades'),
        ),
    ]
