# Generated by Django 4.2 on 2024-11-03 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enfermedades', '0001_initial'),
        ('cita', '0002_alter_cita_fecha_de_cita_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_cita',
            name='ID_Cita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='cita.cita', verbose_name='Cita No'),
        ),
        migrations.AlterField(
            model_name='detalle_cita',
            name='ID_Enfermedades',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='enfermedades.enfermedades', verbose_name='Enfermedad'),
        ),
    ]
